const {QUEUE_NAME_FUTURE, FUTURE_SENTIMENT_TABLE } = Deno.env.toObject();

const BATCH_SIZE = 10;
const VISIBILITY_TIMEOUT = 30;
const QUEUE_NAME = QUEUE_NAME_FUTURE;

export { BATCH_SIZE, QUEUE_NAME, VISIBILITY_TIMEOUT, FUTURE_SENTIMENT_TABLE };