const { QUEUE_NAME_EQUITY, EQUITY_SENTIMENT_TABLE } = Deno.env.toObject();

const BATCH_SIZE = 10;
const VISIBILITY_TIMEOUT = 30;
const QUEUE_NAME = QUEUE_NAME_EQUITY;

export { QUEUE_NAME, VISIBILITY_TIMEOUT, BATCH_SIZE, EQUITY_SENTIMENT_TABLE };