const { QUEUE_NAME_OPTION, OPTION_SENTIMENT_TABLE, OPTION_SENTIMENT_PAYLOAD_TABLE } = Deno.env.toObject();

const BATCH_SIZE         = 10;
const VISIBILITY_TIMEOUT = 30;
const QUEUE_NAME        = QUEUE_NAME_OPTION;

export { QUEUE_NAME, VISIBILITY_TIMEOUT, BATCH_SIZE, OPTION_SENTIMENT_TABLE, OPTION_SENTIMENT_PAYLOAD_TABLE };